### ISSUE TITLE
Implement new route creation in figma

### ISSUE THREAD

**Issue by changchuntzu0618** [cs311-EPFL-StepQuest/ApplicationCode#10]
Creating new route 1: press plus button: 1. start create route -> show where the person is with a pin and start tracking the route 2. plus button become one stop route button and one check point button
Creating new route 2: press stop route button: 1. finish creating route -> store the route in database 2. change stop route button and checkpoint button back to plus button
Creating new route 3: press checkpoint (for putting treasure along route): 1.show a pop up window to let user name the checkpoint (ex. Name: enter checkpoint name) and a button link to start taking picture.

**Comment by Santboneless** [comment]
To be reviewed and approved
