### ISSUE TITLE
Design the figma for search routes

### ISSUE THREAD

**Issue by changchuntzu0618** [cs311-EPFL-StepQuest/ApplicationCode#100]

**Comment by changchuntzu0618** [comment]
Design the Figma for searching the route flow. At initial screen, if should show all the closet routes near the user's current location, and then if the user type a location inside the search box. After press search, the map should zoom into the typing location and show all closet routes near it.

**Comment by simoandreani** [comment]
The design looks good to me, one thing we may want to add is the option to go back to the current location after a search, like placing a button or something.

**Comment by changchuntzu0618** [comment]
> The design looks good to me, one thing we may want to add is the option to go back to the current location after a search, like placing a button or something.

Thanks for your reply. Now, I add a delete button at the right side of the search bar. The delete button should clean all the text in the serch bar, and when the search bar is empty, the map should go back to the current position of user.
